services:
  # php-fpm 7.3
  php81:
    build:
      context: .
      dockerfile: ./php/Dockerfile81
    container_name: local-php
    tty: true
    restart: unless-stopped
    volumes:
      - ./www:/data/www
    networks:
      - grafana

  php-fpm81:
    build:
      context: .
      dockerfile: ./php/fpm/Dockerfile81
    container_name: php_fpm
    restart: unless-stopped
    volumes:
      - ./www:/data/www
    ports:
      - 9000:9000
    networks:
      - grafana

  # nginx
  nginx:
    image: nginx:latest
    container_name: local-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./www:/data/www
    environment:
      - TZ=Asia/Taipei
    networks:
      - grafana

  node:
    image: node:14-alpine
    container_name: node
    tty: true
    ports:
      - 3000:8080
    volumes:
      - ./www:/data/www
    networks:
      - grafana

  # mysql
  mysql:
    image: mysql:5.7
    container_name: local-mysql
    restart: always
    ports:
      - 3306:3306
    command:
      - --innodb-buffer-pool-size=64M
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "aaaa1111"
      MYSQL_DATABASE: "mysql"
      MYSQL_USER: "phil_hsu"
      MYSQL_PASSWORD: "aaaa1111"
    networks:
      - grafana

networks:
  grafana: