services:
  # php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: ./php/fpm/Dockerfile
    container_name: php_fpm_new
    restart: unless-stopped
    volumes:
      - ./www:/data/www
    ports:
      - 9000:9000
    networks:
      - grafana

  # nginx
  nginx:
    image: nginx:latest
    container_name: local-nginx-new
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./www:/data/www
    environment:
      - TZ=Asia/Taipei
    networks:
      - grafana

  # mysql
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: local-mysql-new
    restart: always
    ports:
      - 3306:3306
    command:
      - --innodb-buffer-pool-size=64M
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "aaaa1111"
      MYSQL_DATABASE: "laravel"
      MYSQL_USER: "josh_chen"
      MYSQL_PASSWORD: "tp6rup4djp"
    networks:
      - grafana
networks:
  grafana: